<?php
// Include authentication and game header
require_once '../includes/auth_functions.php';
require_once '../includes/game_header.php';

// Debug - log authentication status
$isUserLoggedIn = isLoggedIn();
error_log("Roulette game accessed - User logged in: " . ($isUserLoggedIn ? "Yes" : "No") . 
          ", Username: " . ($_SESSION['username'] ?? 'not set') .
          ", User ID: " . ($_SESSION['user_id'] ?? 'not set'));

$show_last_win = true; // Enable last win display for this game

// Set flag to hide username and logout in navigation
$hideUsernameAndLogout = true;
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WinXtream - Roulette</title>
    <?php require_once '../fix-mobile.php'; ?>
    <link rel="stylesheet" href="style.css">
    <!-- Add responsive CSS -->
    <link rel="stylesheet" href="/shared-responsive.css">
    <style>
        .add-money-btn {
            display: inline-block;
            margin-left: 5px;
            width: 20px;
            height: 20px;
            background-color: #4CAF50;
            color: white;
            border-radius: 50%;
            text-align: center;
            line-height: 20px;
            text-decoration: none;
            font-weight: bold;
            cursor: pointer;
            transition: background-color 0.3s;
        }
        .add-money-btn:hover {
            background-color: #45a049;
        }
    </style>
</head>

<body>
    <?php require_once '../includes/navigation.php'; ?>

    <div class="content-container">
        <div class="game-header">
            <div class="game-title">Roulette</div>
            <div class="timer-container">
                <svg class="timer-icon" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                    <path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z" />
                    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z" />
                </svg>
                Next number in: <span class="timer" id="timer">15</span>s
            </div>
        </div>

        <div class="game-grid">
            <div class="grid-container" id="number-grid">
                <!-- Grid will be generated by JavaScript -->
            </div>
        </div>

        <div class="betting-panel">
            <div class="bet-panel">
                <div class="panel-header">Place Your Bet</div>
                <div class="bet-input">
                    <input type="number" id="bet-amount" placeholder="Enter bet amount" min="1">
                    <button class="bet-btn" id="bet-button">Place Bet</button>
                </div>

                <div class="slider-container">
                    <div class="slider-label">
                        <span>Bet the number will be less than: <span id="slider-value">50</span></span>
                    </div>
                    <input type="range" id="number-slider" class="slider" min="1" max="93" value="50">
                    <div class="multiplier">
                        <span id="multiplier-value">4.29</span>x
                    </div>
                    <div class="multiplier-info">
                        <span>Lower number = Higher return</span>
                        <span>1.03x - 8.00x</span>
                    </div>
                </div>

                <div id="bet-info">
                    Choose a bet amount and number to begin.
                </div>
            </div>

            <div class="history-panel">
                <div class="panel-header">Game History</div>
                <div class="history-list" id="history-list">
                    <!-- History will be populated by JavaScript -->
                </div>
            </div>
        </div>

        <div class="result" id="result-container">
            <!-- Results will appear here -->
        </div>
    </div>

    <!-- Notification -->
    <div class="notification" id="notification"></div>

    <!-- Add shared responsive JavaScript file -->
    <script src="/shared-responsive.js"></script>
    <!-- Add wallet.js for database integration with cache busting -->
    <script src="/includes/wallet.js?v=<?php echo time(); ?>"></script>
    <script src="script.js"></script>
</body>

</html> 