<?php
// Include authentication and game header
require_once '../includes/game_header.php';
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WinXtream - Roulette</title>
    <link rel="stylesheet" href="style.css">
</head>

<body>
    <nav class="navbar">
        <div class="logo-section">
            <div class="logo"><img src="/Home-Page/Asset/WinXStream-removebg-preview.png" alt="WinXtream"></div>
            <div class="nav-links">
                <a href="/index.php">Home</a>
                <a class="active" href="#">Roulette</a>
                <a href="/mines/mines.php">Mines</a>
                <a href="/crash-game/crash.php">Crash</a>
                <a href="/ColorTrad/color-trade.php">Color Trading</a>
            </div>
        </div>
        <div class="wallet-section">
            <div class="wallet-balance">
                <svg class="wallet-icon" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                    <path
                        d="M12.136.326A1.5 1.5 0 0 1 14 1.78V3h.5A1.5 1.5 0 0 1 16 4.5v9a1.5 1.5 0 0 1-1.5 1.5h-13A1.5 1.5 0 0 1 0 13.5v-9a1.5 1.5 0 0 1 1.432-1.499L12.136.326zM5.562 3H13V1.78a.5.5 0 0 0-.621-.484L5.562 3zM1.5 4a.5.5 0 0 0-.5.5v9a.5.5 0 0 0 .5.5h13a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-13z" />
                </svg>
                $<span id="wallet-display"><?php echo number_format($wallet_balance, 2); ?></span>
            </div>
            <div class="wallet-balance">
                Last Win: $<span id="last-win">0</span>
            </div>
        </div>
    </nav>

    <div class="content-container">
        <div class="game-header">
            <div class="game-title">Roulette</div>
            <div class="timer-container">
                <svg class="timer-icon" width="16" height="16" fill="currentColor" viewBox="0 0 16 16">
                    <path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z" />
                    <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z" />
                </svg>
                Next number in: <span class="timer" id="timer">15</span>s
            </div>
        </div>

        <div class="game-grid">
            <div class="grid-container" id="number-grid">
                <!-- Grid will be generated by JavaScript -->
            </div>
        </div>

        <div class="betting-panel">
            <div class="bet-panel">
                <div class="panel-header">Place Your Bet</div>
                <div class="bet-input">
                    <input type="number" id="bet-amount" placeholder="Enter bet amount" min="1">
                    <button class="bet-btn" id="bet-button">Place Bet</button>
                </div>

                <div class="slider-container">
                    <div class="slider-label">
                        <span>Bet the number will be less than: <span id="slider-value">50</span></span>
                    </div>
                    <input type="range" id="number-slider" class="slider" min="1" max="93" value="50">
                    <div class="multiplier">
                        <span id="multiplier-value">4.29</span>x
                    </div>
                    <div class="multiplier-info">
                        <span>Lower number = Higher return</span>
                        <span>1.03x - 8.00x</span>
                    </div>
                </div>

                <div id="bet-info">
                    Choose a bet amount and number to begin.
                </div>
            </div>

            <div class="history-panel">
                <div class="panel-header">Game History</div>
                <div class="history-list" id="history-list">
                    <!-- History will be populated by JavaScript -->
                </div>
            </div>
        </div>

        <div class="result" id="result-container">
            <!-- Results will appear here -->
        </div>
    </div>

    <!-- Notification -->
    <div class="notification" id="notification"></div>

    <!-- Add wallet.js for database integration with cache busting -->
    <script src="/includes/wallet.js?v=<?php echo time(); ?>"></script>
    <script src="script.js"></script>
</body>

</html> 